version: '3.8'
services:
    spring-boot-deploy_db:
      container_name: spring-boot-deploy_db
      image: postgres:15-alpine
      restart: on-failure
      ports:
        - "5438:5432"
      environment:
        POSTGRES_PASSWORD: example